### ISSUE TITLE
Panic when running `basic` example on M1 Mac

### ISSUE THREAD

**Issue by rparrett** [443eb9/bevy_incandescent#1]
Not sure if your plugin is really meant to be discovered / used right now, so apologies if this is premature.

## `bevy_incandescent` version

f06373be97589f1c21eb0ae0123eba7a7b6bc760

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What I did

`cargo run --example basic`

## Error

```
2024-03-01T20:31:14.933738Z ERROR system{name="bevy_render::renderer::render_system"}:run_graph{name="main_graph"}:run_graph{name="Core2d"}:node{name="bevy_incandescent::render::graph::Shadow2dDistortPassNode"}: log: Handling wgpu errors as fatal by default    
   0: bevy_render::renderer::graph_runner::node
           with name="bevy_incandescent::render::graph::Shadow2dDistortPassNode"
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/renderer/graph_runner.rs:194
   1: bevy_render::renderer::graph_runner::run_graph
           with name="Core2d"
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/renderer/graph_runner.rs:88
   2: bevy_render::renderer::graph_runner::run_graph
           with name="main_graph"
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/renderer/graph_runner.rs:90
   3: bevy_ecs::system::function_system::system
           with name="bevy_render::renderer::render_system"
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.0/src/system/function_system.rs:47
thread '<unnamed>' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.2/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
      note: label = `shadow_2d_distort_pass_bind_group`
    The adapter does not support read access for storages texture of format Rg32Float


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in exclusive system `bevy_render::renderer::render_system`!

thread 'Compute Task Pool (3)' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
   0: bevy_app::app::bevy_app
             at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.0/src/app.rs:300
thread 'main' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.12/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by 443eb9** [comment]
That's because I'm using texture in `Rg32Float` format for shadow maps, which seems to be not supported by MacOS. I'm going to add a feature to force using more common formats like `Rgba32Float` in the future.

Anyway, this is a good issue. I often sacrifice compatibility for performance.

**Comment by 443eb9** [comment]
Feature `compatibility` added. Issue solved.
